apiVersion: apps/v1
kind: Deployment
metadata:
  name: skillpath-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: skillpath-backend
  template:
    metadata:
      labels:
        app: skillpath-backend
    spec:
      containers:
      - name: backend
        image: skillpath-backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql-service:3306/skillpath"
        - name: SPRING_DATASOURCE_USERNAME
          value: "root"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "password"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: skillpath-backend
  ports:
  - port: 8080
    targetPort: 8080
  type: LoadBalancer